apiVersion: kustomize.config.k8s.io/v1beta1

kind: Kustomization
resources:
- deployment.yaml
namespace: default
images:
- name: backend-image-prod
  newName: ikcap/disk_backend
  newTag: 9c6294f87808d086c2e94f5dbb1b3eb7bb22883f
- name: frontend-image-prod
  newName: ikcap/disk_frontend_neuro
  newTag: c1ceca05b86cdf86e80f488468127ff5f5a508b8
