kind: ConfigMap 
apiVersion: v1 
metadata:
  name: server-properties
data:
  server.properties: | 
    {
        server = http://localhost:8080/disk-server;
        storage = 
        {
            local = /root/disk/storage;
            tdb = /root/disk/storage/TDB;
            db = /root/disk/storage/DB;
        }
        keycloak =
        {
            url = https://auth.mint.isi.edu;
            realm = production;
        }
        data-adapters = 
        {
            Bikes-rental = 
            {
                type = sparql;
                endpoint = https://endpoint.mint.isi.edu/tutorial;
            }
        }
        method-adapters =
        {
            wings_bikes =
            {
                type = wings;
                endpoint = https://wings.disk.isi.edu/wings-portal;
                username = admin;
                password = 4dm1n!23;
                internal_server = https://wings.disk.isi.edu/wings-portal;
                domain = bikes;
            }
        }
        question-templates =
        {
            bikes = https://raw.githubusercontent.com/KnowledgeCaptureAndDiscovery/QuestionOntology/main/examples/bike_rent.xml;
        }
        vocabularies =
        {
            disk-hypothesis =
            {
                url = https://knowledgecaptureanddiscovery.github.io/DISK-Ontologies/hypothesis/release/0.0.2/ontology.owl;
                prefix = hyp;
                namespace = http://disk-project.org/ontology/hypothesis#;
                description = "The DISK Hypothesis Ontology. Defines properties to be used on Hypothesis creation.";
            }
        }
    }
