apiVersion: kustomize.config.k8s.io/v1beta1

kind: Kustomization
resources:
- deployment.yaml
namespace: default
images:
- name: backend-image-prod
  newName: ikcap/disk_backend_climate
  newTag: c7fd1f3a69e229817d224cc16b7539f55139e133
- name: frontend-image-prod
  newName: ikcap/disk_frontend_climate
  newTag: a11158b40f69d423c5936ec6a7198f1e2361539e
