apiVersion: kustomize.config.k8s.io/v1beta1

kind: Kustomization
resources:
- deployment.yaml
namespace: default
images:
- name: backend-image-prod
  newName: ikcap/disk_backend
  newTag: 989aa0945764f8f8f47edbfa14aeae8dd370d1d4
- name: frontend-image-prod
  newName: ikcap/disk_frontend_climate
  newTag: 44e47ab4d3c35a1ebbd8f43eaf3db1ff80d63e29
