apiVersion: kustomize.config.k8s.io/v1beta1

kind: Kustomization
resources:
- deployment.yaml
namespace: default
images:
- name: backend-image-prod
  newName: ikcap/disk_backend
  newTag: 4a14ece73f178450f0d85256bcb11e04157a72c7
- name: frontend-image-prod
  newName: ikcap/disk_frontend_climate
  newTag: 004687ce5450b05bd17891f92f8303a809c7dc90
