apiVersion: v1
kind: Service
metadata:
  name: wings-disk-dev
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 7080
---
apiVersion: v1
kind: Endpoints
metadata:
  name: wings-disk-dev 
subsets:
  - addresses:
      - ip: 10.0.1.1
    ports:
      - port: 7080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wings-disk-dev-ingress
  annotations:
    kubernetes.io/ingress.class: public
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
    - hosts:
      - wings.dev.disk.isi.edu
      secretName: wings-disk-dev-tls
  rules:
    - host: wings.dev.disk.isi.edu
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: wings-disk-dev
                port:
                  number: 80
