apiVersion: kustomize.config.k8s.io/v1beta1

kind: Kustomization
resources:
- deployment.yaml
namespace: default
images:
- name: backend-image-prod
  newName: ikcap/disk_backend
  newTag: 16bed4ad4cb53003fb79250223b155136b7e8932
- name: frontend-image-prod
  newName: ikcap/disk_frontend
  newTag: 44e47ab4d3c35a1ebbd8f43eaf3db1ff80d63e29
