apiVersion: kustomize.config.k8s.io/v1beta1

kind: Kustomization
resources:
- deployment.yaml
namespace: default
images:
- name: backend-image-prod
  newName: ikcap/disk_backend
  newTag: 3af64a942b7af147ad3eceb1d9a4f13bcb1e2bef
- name: frontend-image-prod
  newName: ikcap/disk_frontend
  newTag: a11158b40f69d423c5936ec6a7198f1e2361539e
