apiVersion: kustomize.config.k8s.io/v1beta1

kind: Kustomization
resources:
- deployment.yaml
namespace: default
images:
- name: backend-image-prod
  newName: ikcap/disk_backend
  newTag: 6bf99d43b45985895e5a83c8ae09f77de5e49cdf
- name: frontend-image-prod
  newName: ikcap/disk_frontend
  newTag: aa7fd83f85b37a543024a2ea07a16bb91a2191ce
