apiVersion: kustomize.config.k8s.io/v1beta1

kind: Kustomization
resources:
- deployment.yaml
namespace: default
images:
- name: backend-image-prod
  newName: ikcap/disk_backend
  newTag: 107e36f303a6dafd64b87b93996eb31d446147fc
- name: frontend-image-prod
  newName: ikcap/disk_frontend
  newTag: 44e47ab4d3c35a1ebbd8f43eaf3db1ff80d63e29
