apiVersion: kustomize.config.k8s.io/v1beta1

kind: Kustomization
resources:
- deployment.yaml
namespace: default
images:
- name: backend-image-prod
  newName: ikcap/disk_backend
  newTag: 791c9ecc4576543723f896a773bfb58223f2936a
- name: frontend-image-prod
  newName: ikcap/disk_frontend
  newTag: aa7fd83f85b37a543024a2ea07a16bb91a2191ce
