apiVersion: kustomize.config.k8s.io/v1beta1

kind: Kustomization
resources:
- deployment.yaml
namespace: default
images:
- name: backend-image-prod
  newName: ikcap/disk_backend
  newTag: 987bcf8d9aa0c6d326befe435f3a0f0a6aee47a2
- name: frontend-image-prod
  newName: ikcap/disk_frontend
  newTag: b261baabc971a0bf2a9868b13e94351799f63bbe
