apiVersion: kustomize.config.k8s.io/v1beta1

kind: Kustomization
resources:
- deployment.yaml
namespace: default
images:
- name: backend-image-prod
  newName: ikcap/disk_backend
  newTag: b47d422c681dcf52add4f6df9ab9f11c767b0402
- name: frontend-image-prod
  newName: ikcap/disk_frontend
  newTag: 8e259746a26a14de26a93abbe4648a0039e92c16
