apiVersion: kustomize.config.k8s.io/v1beta1

kind: Kustomization
resources:
- deployment.yaml
namespace: default
images:
- name: backend-image-prod
  newName: ikcap/disk_backend
  newTag: 5e927b307d0d5e828e2044ca6f7e94403c41cce8
- name: frontend-image-prod
  newName: ikcap/disk_frontend
  newTag: 9bdceec5a3ffc4b5f35af4dd64c3862e6b037a68
