apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wings-prod-pv-claim
spec:
  storageClassName: microk8s-hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi