apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-cd
spec:
  selector:
    matchLabels:
      app: demo-cd
  replicas: 1
  template:
    metadata:
      labels:
        app: demo-cd
    spec:
      containers:
        - name: demo-cd
          image: demo-cd
          ports:
            - containerPort: 80