apiVersion: v1
kind: Service
metadata:
  name: disk-frontend-dev
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: disk-dev
---
apiVersion: v1
kind: Service
metadata:
  name: disk-backend-dev
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: disk-dev
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: disk-dev
spec:
  selector:
    matchLabels:
      app: disk-dev
  replicas: 1
  template:
    metadata:
      labels:
        app: disk-dev
    spec:
      containers:
        - name: disk-dev
          image: frontend-image-dev
          ports:
            - containerPort: 80
        - name: backend
          image: backend-image-dev
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: server-properties
              mountPath: /root/.disk/
      volumes:
        - name: server-properties
          configMap:
            name: server-properties 
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: disk-frontend-dev-ingress
  annotations:
    kubernetes.io/ingress.class: public
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
    - hosts:
      - dev.disk.isi.edu
      secretName: disk-frontend-dev-tls
  rules:
    - host: dev.disk.isi.edu
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: disk-frontend-dev 
                port:
                  number: 80
          - pathType: Prefix
            path: "/disk-server"
            backend:
              service:
                name: disk-backend-dev 
                port:
                  number: 80
