apiVersion: kustomize.config.k8s.io/v1beta1

kind: Kustomization
resources:
- deployment.yaml
namespace: default
images:
- name: backend-image-prod
  newName: ikcap/disk_backend
  newTag: latest 
- name: frontend-image-prod
  newName: ikcap/disk_frontend
  newTag: latest 
