apiVersion: kustomize.config.k8s.io/v1beta1

kind: Kustomization
resources:
- deployment.yaml
namespace: default
images:
- name: backend-image-dev
  newName: ikcap/disk_backend
  newTag: 489c2209df43d1007e72571d5fe4ac10340ea0c7 
- name: frontend-image-dev
  newName: ikcap/disk_frontend
  newTag: 122e5c8a90c88a64db96e915e385b4955fb2710c 
