apiVersion: v1
kind: Service
metadata:
  name: nagios-internal
  namespace: default
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
---
apiVersion: v1
kind: Endpoints
metadata:
  name: nagios-internal
subsets:
  - addresses:
      - ip: 10.0.1.1
    ports:
      - port: 8080

